### PR TITLE
chore: add github action

### PR DESCRIPTION
**Pull request by watonyweng**
1. add ci script
2. add deploy script

### CODE REVIEW

**Comment by watonyweng** [comment]
@sunface Hi, could you please approve this pr?

**Comment by sunface** [comment]
> @sunface Hi, could you please approve this pr?

不好意思，回复晚了，我看下哈

**Review by sunface — APPROVED** [review]
好好好，太需要这个了，很棒！

**Comment by watonyweng** [comment]
@sunface #1426 修复了CI运行时的 `mdbook test` 错误

**Pull request merged**
